### ISSUE TITLE
[Feature Request] Make DELETE operations return the number of deleted rows

### ISSUE THREAD

**Issue by scottsand-db** [delta-io/delta#1222]
### Overview

Currently, the `DELETE` operation returns an empty result. It would be more useful if it returned the number of deleted rows.

### Motivation

The number of deleted rows is an obvious metric that users would want from a delete operation.

### Further details

Currently, `DeleteCommand.scala` is explicitly returning an empty `DataFrame` [here](https://github.com/delta-io/delta/blob/master/core/src/main/scala/org/apache/spark/sql/delta/commands/DeleteCommand.scala#L98). Instead, we could use the `metrics` member field to return the `numDeletedRows`.

Make sure to add tests, too :)

**Comment by edmondo1984** [comment]
I would be happy to look into that

**Comment by edmondo1984** [comment]
@scottsand-db I had a look at the RunnableCommand and I hadn't grasped the meaning of the returned row. If I understood it correctly, this change should be sufficient.

https://github.com/edmondo1984/delta/commit/17998f4ca58f98fe808ce68114a44349ea345966

I wanted to get feedback around the design before adding the tests, I hadn't opened a PR yet for this reason. It's my first contribution, so rather than implementing tests for the wrong thing, I wanted to double check if I understood the API

**Comment by scottsand-db** [comment]
@edmondo1984 i left some comments. Make some small changes then make the PR! I can help with ways to add tests, too. thanks for helping!
