### ISSUE TITLE
No new version after ALTER TABLE SET TBLPROPERTIES 

### ISSUE THREAD

**Issue by jaceklaskowski** [delta-io/delta#1310]
It was reported on [slack](https://delta-users.slack.com/archives/CJ70UCSHM/p1659592875176129?thread_ts=1659438345.392989&cid=CJ70UCSHM):

> upon checking the table history I saw no changes have come in effect, there was no entry in the table history of enabling the CDF.

>     ALTER TABLE merge_demo
>     SET TBLPROPERTIES (delta.enableChangeDataFeed = true);

The idea behind this issue is to fix it in the code (and perhaps create a new version) or in the docs (explaining the proper behaviour).

**Comment by jaceklaskowski** [comment]
`ALTER TABLE SET TBLPROPERTIES` does create a new version:

```
+-------+-----------------+-----------------------------------------------------------------------------+
|version|operation        |operationParameters                                                          |
+-------+-----------------+-----------------------------------------------------------------------------+
|1      |SET TBLPROPERTIES|{properties -> {"delta.enableChangeDataFeed":"true"}}                        |
|0      |CREATE TABLE     |{isManaged -> true, description -> null, partitionBy -> [], properties -> {}}|
+-------+-----------------+-----------------------------------------------------------------------------+
```

**Comment by nkarpov** [comment]
I will close since Yatharth [confirmed it was a configuration error](https://delta-users.slack.com/archives/CJ70UCSHM/p1659619364595169?thread_ts=1659438345.392989&cid=CJ70UCSHM).

For reference, the `ALTER TABLE SET TBLPROPERTIES` command creates & attempts to commit a new transaction by design.

https://github.com/delta-io/delta/blob/master/core/src/main/scala/org/apache/spark/sql/delta/commands/alterDeltaTableCommands.scala#L105-L124
