### ISSUE TITLE
Is there any plan to support Google Cloud Storage

### ISSUE THREAD

**Issue by majbilou** [delta-io/delta#134]
Hi,

Is there any plan to support Google Cloud Storage

Thank you in advance

**Comment by mukulmurthy** [comment]
Hi @majbilou, here are the requirements for the underlying storage system in order to maintain ACID guarantees:
https://github.com/delta-io/delta#requirements-for-underlying-storage-systems

HDFS over Google Cloud will work out of the box; I'm not familiar enough with Google Cloud Storage to know if they have these guarantees. If they don't, writing a plugin to support Google Cloud Storage isn't on our immediate roadmap, but we'd be happy to point you to the AWS and Azure implementations to show how they solve these problems.

**Comment by majbilou** [comment]
Thank you @mukulmurthy for the feedback
