### ISSUE TITLE
[BUG] Delta log for timetravel queries seems to be cached incorrectly

### ISSUE THREAD

**Issue by george-zubrienko** [delta-io/delta#1479]
### Describe the problem

When joining two different versions from the same table, produced result is incorrect.

#### Steps to reproduce

Given the following table:

```
-- create version 0
create table dev_george_t.bug_table using delta as
select 1L as colA, 'abc' as colB

-- insert version 1
insert into dev_george_t.bug_table
select 2L as colA, 'cde' as colB
```

Running `describe history dev_george_t.bug_table` outputs 2 rows (version 0 and version 1) as expected. Now let's create two views:

```
create or replace temporary view a as select * from dev_george_t.bug_table version as of 0;
create or replace temporary view b as select * from dev_george_t.bug_table version as of 1;
```

Finally, let's join them:

```
select b.* from b left join a as a on a.colA = b.colA where a.colA is null
```

Now let's materialize view `a` and run the query against it instead:

```
create table dev_george_t.bug_a using delta as select * from a
select b.* from b left join dev_george_t.bug_a as a on a.colA = b.colA where a.colA is null
```

#### Observed results

Both views:

| colA  | colB  |
|---|---|

View and a table:

| colA  | colB  |
|---|---|
| 2  | cde  |

#### Expected results
Both cases:

| colA  | colB  |
|---|---|
| 2  | cde  |

#### Further details

This has been confirmed on OSS delta, haven't tried on databricks one.

Same issue occurs if CTEs are used instead of temporary views. If either/both versions are materialized in a separate table, then join returns correct result.

### Environment information

* Delta Lake version: 2.1.1
* Spark version: 3.3.1
* Scala version: N/A

### Willingness to contribute

The Delta Lake Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the Delta Lake code base?

- [x] No. I cannot contribute a bug fix at this time.

**Comment by allisonport-db** [comment]
Thanks for reporting this. I think you switched a few things in the examples but I'm seeing
```
scala> spark.sql("select * from a right join b on a.colA = b.colA").show()
+----+----+----+----+
|colA|colB|colA|colB|
+----+----+----+----+
|   1| abc|   1| abc|
+----+----+----+----+


scala> spark.sql("select * from b left join a on a.colA = b.colA").show()
+----+----+----+----+
|colA|colB|colA|colB|
+----+----+----+----+
|   1| abc|   1| abc|
|   2| cde|   2| cde|
+----+----+----+----+
```

**Comment by george-zubrienko** [comment]
@allisonport-db thanks for sorting out my mess there :) I've updated the issue description accordingly and added an example with table materialization

**Comment by allisonport-db** [comment]
@george-zubrienko so I took a look at this and it seems to be an issue with the way Spark caches resolved relations. I've opened [SPARK-41154](https://issues.apache.org/jira/browse/SPARK-41154).

Basically, in Spark when we resolve the first relation we cache it [here](https://github.com/apache/spark/blob/master/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/Analyzer.scala#L1250) with key="spark_catalog.default.bug_table" (or whatever the fully qualified table name is). Then when we resolve the second relation we successfully lookup the cached relation [here](https://github.com/apache/spark/blob/master/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/Analyzer.scala#L1242) _**since the key doesn't include time travel information**_ and we resolve to whatever the first resolved relation was **_ignoring the timeTravelSpec_**.

This affects SQL queries with time-travel subqueries or CTEs, and temp views created with SQL using time travel in Delta 2.1/ Spark 3.3 (first versions to support time-travel SQL syntax).

This doesn't affect views created using the Dataset API so the following will work as expected:
```
spark.sql("select * from issue_1479 version as of 0").createOrReplaceTempView("a")
spark.read.format("delta").option("versionAsOf", version).createOrReplaceTempView("a")
```
As a workaround for views, you can set `spark.conf.set("spark.sql.legacy.storeAnalyzedPlanForView", true)` which prevents the view from being re-resolved in subsequent queries (and incorrectly looked up from the cache).

Thanks for bringing this up, we will work to get a fix into spark

**Comment by allisonport-db** [comment]
Also just to add an example here, queries like this are also incorrect
```sql
select * from table version as of 1
union all
select * from table version as of 0
```
--(resolved)-->
```sql
select * from table version as of 1
union all
select * from table version as of 1
```

**Comment by george-zubrienko** [comment]
@allisonport-db thanks a lot for a detailed investigation and explanation. We'll use the workaround you mentioned until this is resolved!
