### ISSUE TITLE
After renaming External location for Delta Lake Table, Alter set location doesn't work

### ISSUE THREAD

**Issue by tintinmj** [delta-io/delta#154]
I created an external Delta Lake table pointing to a location. Then rename the location folder. Then tried to alter the location. It gives me an error saying `Error in SQL statement: AnalysisException: ``<table>`` is not a Delta table.;`

I am attaching the MCVE notebook. Extract the `Delta-bug.zip` and you will get the Databricks Notebook.

[Delta-bug.zip](https://github.com/delta-io/delta/files/3581057/Delta-bug.zip)

**Comment by mukulmurthy** [comment]
Hi @tintinmj ,

GitHub issues are for OSS Delta Lake bugs, feature requests, and discussions. If you have an issue with Delta Lake on Databricks, please file a support ticket.

**Comment by tintinmj** [comment]
@mukulmurthy where to file that? Isn't Delta Lake is a part of Databricks?

**Comment by mukulmurthy** [comment]
Hi @tintinmj ,

Delta Lake is a project developed by Databricks and open sourced here under the organization delta.io. There are minor differences between Managed Delta Lake (which you get automatically if running on Databricks) and OSS Delta Lake in this repository - see [here](https://github.com/delta-io/delta#roadmap). We try to keep the support channels separate, both because the Databricks paid support has better SLAs and so future viewers here see relevant topics for their flavor of Delta Lake.

If there's an issue with Managed Delta Lake on Databricks, you can ask either [on Slack](https://github.com/delta-io/delta#community) or by filing a [Databricks support ticket](https://docs.databricks.com/support.html#create-a-support-case).
