### ISSUE TITLE
[BUG] rowTracking should be a reader/writer Table Feature?

### ISSUE THREAD

**Issue by felipepessoto** [delta-io/delta#1895]
### Describe the problem
rowTracking is describe as writer only:

![image](https://github.com/delta-io/delta/assets/1336227/88038221-729e-49f0-aaed-93a7b3beb482)

But we do have required changes on reader side, for example to hide materializedRowIdColumnName and also "Readers cannot read Row IDs and Row Commit Versions while reading change data files from cdc actions."

I think it is not safe to allow a reader to read incorrect data.

#### Steps to reproduce

N/A

#### Observed results

N/A

#### Expected results

N/A

#### Further details

N/A

### Environment information

N/A

### Willingness to contribute

The Delta Lake Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the Delta Lake code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the Delta Lake community.
- [ ] No. I cannot contribute a bug fix at this time.

**Comment by tomvanbussel** [comment]
There should be no changes on the reader side necessary. Readers are already expected to only read the columns that are in the schema of the latest metadata action. Therefore, they should already ignore the materialized row id and row commit version columns in the Parquet files, if they do want to read these metadata columns (in this case because they do not know that these metadata columns exist).

I do agree that it is a bit weird to mark this feature as writer-only feature, even though there is a large reader-side component to it. However, this is not unlike Change Data Feed, for example, which is also a writer-only feature, even though reading the CDF requires large reader-side changes. The advantage of making this a writer-only feature is that it does not break the ability of older implementations of Delta Lake to read the table.

**Comment by felipepessoto** [comment]
Got it. Thanks for explaining.
