### ISSUE TITLE
Three main package names in the project

### ISSUE THREAD

**Issue by MrPowers** [delta-io/delta#204]
The [DeltaLog](https://github.com/delta-io/delta/blob/master/src/main/scala/org/apache/spark/sql/delta/DeltaLog.scala) package name is `org.apache.spark.sql.delta`.  I think the `DeltaLog` I'm trying to import is conflicting with another `DeltaLog` on the cluster.

I took a look at the Delta Lake JAR file contents with the `jar tvf delta-core_2.11-0.4.0.jar | less` command and looks like these namespaces are all included:

* `com.databricks`
* `org.apache.spark`
* `io.delta`

Maybe we should consider getting all the code in the `io.delta` namespace?  Or perhaps we can shade the `com.databricks` and `org.apache.spark` stuff?

**Comment by marmbrus** [comment]
All public / stable APIs of delta should be in `io.delta`. If not, I agree that is a bug and we should fix it right away.

I believe that all the `org.apache.spark` stuff is due to package private APIs in Spark. While it would be good for cleanliness and compatibility to clean this up, we'd have to investigate if these are stable APIs that Apache Spark would consider opening. The first step would be to compile a list of what APIs we are using that require us to be in `org.apache.spark`.

The `com.databricks` stuff seems to fall into two categories:
 - Fine grained usage logging. We stub out an internal API that we use to collect usage statistics for Delta. We considered removing this, but I actually thing this data could be very useful to someone who is running their own Delta deployment. We could change the package, but that would mean we'd have to build a lot of stubs internally to keep it working. If there is interest in stabilizing / making this API public I would change, but otherwise I'm not sure it is worth the effort.
 - Stuff in `test.com.databricks`.  This seems to be a bug, in our use of copybara.  We should fix this. cc @tdas

**Comment by tdas** [comment]
The `test.com.databricks` only has java test suites and putting them in `test.*` was intentional so that we just followed [Spark's convention ](https://github.com/apache/spark/blob/master/sql/core/src/test/java/test/org/apache/spark/sql/JavaDatasetSuite.java)of putting the java tests into a separate package, mainly for testing package visibility, etc. However, you are right, there is not need for it to be `test.com.databricks`; rather it probably should be `test.io.delta.tables`. Will make a PR to fix it.

**Comment by zsxwing** [comment]
@MrPowers Thanks a lot for your discussion and PR. We prefer to avoid such huge changes with little benefits. Closing this.
