### ISSUE TITLE
delta0.8 use merge，How to improve performance

### ISSUE THREAD

**Issue by myBigbug** [delta-io/delta#2075]
#### Which Delta project/connector is this regarding?

- [x] Spark

### Overview
use Spark-scala API merge delta table. 
for example
```scala
DeltaTable.forPath(spark, "/data/events/")
  .as("events")
  .merge(
    updatesDF.as("updates"),
    "events.eventId = updates.eventId")
  .whenMatched
  .updateExpr(
    Map("data" -> "updates.data"))
  .whenNotMatched
  .insertExpr(
    Map(
      "date" -> "updates.date",
      "eventId" -> "updates.eventId",
      "data" -> "updates.data"))
  .execute()
```

***
my delta table number of partitions 700 and 700 million data, each partition size of 130MB.
How to improve performance,Should I increase or decrease the number of partitions?

**Comment by tdas** [comment]
Delta 0.8 is really old! Can't you use the latest version of Delta?

**Comment by myBigbug** [comment]
> Delta 0.8 is really old! Can't you use the latest version of Delta?

Because my spark version is 3.0，so only delta0.8 can be used @tdas

**Comment by tdas** [comment]
how many files does your table have (use DESCRIBE DETAIL), and how many files is merge rewriting (using DESCRIBE HISTORY to see the merge operation metrics).

**Comment by tdas** [comment]
What about the merge operation metrics?

Basically you need to understand if merge is rewriting entire set of files or only a subset. If its entire set of files are rewritten every time, then that just means your key (eventId in your example) is randomly distributed .. and there is very little you can do. 

merge is a very complex command and its tricky to speed it up. Upgrading the later versions of Delta can help because there has been a lot of optimizations since  0.8. For example in 1.1, there were major optimizations that for merges on partitioned tables - https://delta.io/blog/2021-12-03-delta-release-1-1-0-released/

**Comment by myBigbug** [comment]
thanks @tdas
