### ISSUE TITLE
Support user designation of _delta_log location

### ISSUE THREAD

**Issue by kjthebard** [delta-io/delta#21]
Hi, this is a feature request to support user designated location of the _delta_log folder. While it is possible to create an external table from the parquet files alone; something like Snowflake/Azure Data Warehouse is not able to understand what the _delta_log folder is an errors out when making an external table. Would it be possible to support the ability to designate the save location of the _delta_logs so that these tools can read the folder while still being able to take advantage of Delta? I understand this would complicate the read, as you would need to pass both the parquet location and the _delta_log folder, but would it be better to be explicit rather than implicit here? 

Maybe make the implicit way the default and allow the user the option to  explicitly store these elsewhere?

**Comment by mukulmurthy** [comment]
Hi Kieran,

Reading the underlying data files directly is not guaranteed to return a consistent view of the table; the ACID guarantees of Delta Lake are predicated on going through the transaction log for writes and reads. Even if we moved the _delta_log folder outside of the table, you would not be able to create an external table from that folder.

Once we have SQL DDL/DML support (which we are actively working on), you can use the normal SQL Spark APIs to create Delta tables in the Hive metastore. It might be possible to support other tools reading a snapshot of a Delta table but we have no current plans to support that now.

**Comment by kjthebard** [comment]
Hi Mukul,

Do y'all have a timeline on that SQL DDL/DML support?

**Comment by kjthebard** [comment]
> Even if we moved the _delta_log folder outside of the table, you would not be able to create an external table from that folder.

Do y'all have a recommendation on how to export data from delta to a data warehouse or are we thinking about this wrong.  Should delta be the source for a data warehouse?

**Comment by mukulmurthy** [comment]
SQL support depends on some parsing changes we’d need to make in Spark; we’re hoping to have something in the next couple months. Before then, you can still use the batch or streaming DataFrame APIs (in Scala or Python) to read the table. While you can’t statically look at the data files in your Delta table, Delta does play nicely as a Spark Structured Streaming source with all the usual exactly-once guarantees streaming has.

If you want to use existing data warehouses like Azure SQL DW or Snowflake, you can still use Delta for the ETL processes and use existing Spark connectors to write data out to these services. A fairly typical use case is to also use Delta as a last hop before pushing to a data warehouse, because then the Delta table data can also be used to do ML.

**Comment by kjthebard** [comment]
That seems fine for now! Is there a way for me to track the SQL DDM process?

**Comment by mukulmurthy** [comment]
We're still working on finalizing the processes for this sort of stuff; we'll keep you posted. Thanks for bearing with us while we sort that out!

**Comment by tdas** [comment]
@kjthebard I have created specific issues for building APIs for DMLs like Merge (#42), Update (#43) and Delete (#44). Please vote and have any further discussion on them in those issues. For now, I am closing this issue. Feel free to reopen it if you have more questions on non-DML stuff.
