### ISSUE TITLE
Vacuum a single table partition

### ISSUE THREAD

**Issue by guyneedhamcanva** [delta-io/delta#220]
Is it possible to vacuum a single partition of a Delta table in version 0.4.0? 

With large tables, containing many partitions, the vacuum operation takes a very long time. This is problematic for us. How can we restrict the range of the vacuum operation to only some partitions? 

In our example we vacuum maintaining 8 days of history. Our table is partitioned by date, so we are ignoring the most recent 8 partitions. How can we also limit the scope of the vacuum operation to only vacuum partitions which are between 8 and 10 days old?

**Comment by tdas** [comment]
This is not possible as of now. Vacuum works on the entire table. However if you real problem is the performance of vacuum, then you can control it with two knobs. 

- SQL conf "spark.sql.sources.parallelPartitionDiscovery.parallelism" determines how many parallel tasks will it use list the files present in the directory. Unfortunately, for legacy reasons, the default value of this conf in Apache Spark is 10000 which is often too if the cluster is very small and slows down vacuum unnecessarily.

- Cluster size - obviously larger number of cores (not more than the above conf) helps speed up the file discovery.

**Comment by tdas** [comment]
@guyneedhamcanva any thoughts on this?

**Comment by guyneedhamcanva** [comment]
Hi @tdas, thanks for the config option. Our main difficulty with the vacuum performance is the time taken to delete files from s3. Our testing shows that it takes about 0.7 seconds to delete one file, which is far longer than the listing time. Is there a config option to control parallelism of deleting files?

**Comment by tdas** [comment]
Aah, interesting. As of now there isnt any way because the deletion is single-threaded. We kept it simple and single-threaded because we have observed in some cases, bulk deletion can overwhelm some file systems. But this can be improved probably by making it optionally multi-threaded. Would be an awesome feature contribution ;)

**Comment by redsk** [comment]
@tdas what would a more sensible value of `spark.sql.sources.parallelPartitionDiscovery.parallelism` for small clusters of around 20 to 100 cores?

**Comment by tdas** [comment]
I would probably make it a small multiplier (1x-5x) of the number of cores.

**Comment by zsxwing** [comment]
#522 added the parallel file deletion.
