### ISSUE TITLE
[Kernel] Test `DefaultJsonHandler` for empty JSON files

### ISSUE THREAD

**Issue by allisonport-db** [delta-io/delta#2251]
#### Which Delta project/connector is this regarding?

- [ ] Spark
- [ ] Standalone
- [ ] Flink
- [X] Kernel
- [ ] Other (fill in here)

### Overview

#2211 adds a test for reading empty parquet files (and fixes a bug in our `DefaultParquetReader`). We should test the same for the `DefaultJsonHandler`.

### Further details

We should test `DefaultJsonHandler.readJsonFiles(...)` with a file-list that includes empty JSON files in the middle of the list.

**Comment by fernandocast** [comment]
Hi @allisonport-db,

Is this ticket still open? If so I would like to help on this. 😄

**Comment by fernandocast** [comment]
> @fernandocast are you still interested in working on this issue? Let me know if you have any questions.

Yes, I'm still interested. Sorry, I have been kind of busy but I'm gonna start this week.

**Comment by fernandocast** [comment]
> @fernandocast are you still interested in working on this issue? Let me know if you have any questions.

One question @vkorukanti, I noticed that the method DefaultJsonHandler.readJsonFiles doesn't works well if the list of files contains and empty file in the middle. 
Is this the expected behavior ? or should I fix this and also perform the tests?

**Example of current behaviour:**

_**list of json files**_
1.json -> {non_empty_json}
1_empty.json -> empty
2.json -> {non_empty_json}

in this case the current code just read data from 1.json and stops when it found the empty file.

**Comment by vkorukanti** [comment]
@fernandocast Yep, it is a bug. You can fix it by calling the `hasNext` recursively within the current `hasNext` implementation.

**Comment by ilicmarkodb** [comment]
Hi @allisonport-db, can you please review my PR?
