### ISSUE TITLE
WriteStream append to table does not update _delta_log

### ISSUE THREAD

**Issue by abij** [delta-io/delta#296]
I'm using Databricks runtime 6.2 on Azure Databricks.

According to https://docs.databricks.com/delta/delta-streaming.html#append-mode there are two modes to stream into an existing table.

In both options, the parquet files are written, but only the first option creates new files in delta_logs.
The seconds option does **not** update the delta_logs!

```python
(spark
 .readStream
 .format("kafka")
 .option(...)                           # .. lots of settings
 .load()
 .writeStream
#  .format("delta")                     # option-1: working
 .outputMode("append") 
 .option('checkpointLocation', '/mnt/delta/sample/_checkpoints/etl-from-kafka')
#  .start("/mnt/delta/raw_json")        # option-1: working
 .table('sample.raw_json')              # option-2: no delta_log
)
```

**Comment by mukulmurthy** [comment]
Hi @abij ,

This project is for discussion of OSS Delta Lake, which doesn't include the table() API. Please file a support ticket or post on #deltalake-databricks on Slack and we'd be happy to help more.

I think in your case, it's because you still need that `.format("delta")` bit even when you use `table()`. If it doesn't work without that, we should definitely throw a better error message.

**Comment by abij** [comment]
He @mukulmurthy, I tried to find the proper place to post the issue, but could not find it. I'm unable to find the Slack workspace to join the channel you proposed.

The spark version 2.4.4 does not contain an api call .table() on the .writeStream, it's custom for the Databricks-runtime I suppose.

**Comment by mukulmurthy** [comment]
https://github.com/delta-io/delta#community contains the links to join the Slack channel.

Yeah, the .table() API is a part of Databricks Runtime.
