### ISSUE TITLE
[BUG] Kernel: The kernel AddFile schema miss `tags` field.

### ISSUE THREAD

**Issue by horizonzy** [delta-io/delta#3116]
In the standalone lib, the AddFile has the field Map<String, String> tags.
https://github.com/delta-io/delta/blob/57df2c0c5d1e25e70aac1d5ce5c6ac7dba54d0f9/connectors/standalone/src/main/java/io/delta/standalone/actions/AddFile.java#L52C5-L52C44

In the kernel lib, the AddFile schema misses the field `tags`, we need to make the kernel lib compatible with the standalone lib
https://github.com/delta-io/delta/blob/57df2c0c5d1e25e70aac1d5ce5c6ac7dba54d0f9/kernel/kernel-api/src/main/java/io/delta/kernel/internal/actions/AddFile.java#L50-L58

**Comment by vkorukanti** [comment]
@horizonzy The `AddFile` that you are referring to in Kernel is an internal class. Standalone takes the `AddFile` for data files that need to be added to the Delta Log. As Delta added more features such as column mapping, row tracking, etc., the connectors code became complicated. The connector needs to understand the protocol details of what each field in the `AddField` means and when it is needed. In order to simplify the connector code writing into Delta, Kernel works with the logical data that needs to be written to the table and it takes care of internally creating the `AddFile` and adding to the Delta Log. The usage guide for writing APIs is available [here](As Delta added more features such as column mapping, row tracking, etc.). It has examples of how to [create a table](https://github.com/delta-io/delta/blob/master/kernel/USER_GUIDE.md#create-to-delta-table) and [insert data](https://github.com/delta-io/delta/blob/master/kernel/USER_GUIDE.md#blind-append-into-an-existing-delta-table) into an existing table.

If you want to discuss more about using the APIs, feel free to ping me on [`delta-users`](https://delta-users.slack.com/join/shared_invite/zt-2is7d09as-GFC2bhOUOGjmUTLAF9kOOw#/shared-invite/email) Slack or email `first.last@gmail.com`.  We are also happy to know your use case and address any gaps in the current APIs. We released the preview write APIs in 3.2 and any feedback is useful.
