### ISSUE TITLE
HEAD before PUT consistency in S3SingleDriverLogStore

### ISSUE THREAD

**Issue by igorcalabria** [delta-io/delta#319]
Calling `S3SingleDriverLogStore#write`[1] with overwrite = false will cause the underlying fs implementation to issue a HEAD request to s3 that will potentially be cached as 404 and this will break the consistency property of the `LogStore`. Since `S3SingleDriverLogStore` already does a listing based existence check[3], we could simply call `fs.create` with overwrite=true all times to avoid this issue. 

The tricky part is that this also depends on hadoop version. For hadoop 2.7, I believe no HEAD request are made if overwrite=true. The same can't be said on hadoop 3.2 because it issues a status request anyway[4]. So even with overwrite=true, the consistency issue mentioned can't be avoided. 

[1] https://github.com/delta-io/delta/blob/master/src/main/scala/org/apache/spark/sql/delta/storage/S3SingleDriverLogStore.scala#L167
[2] https://github.com/delta-io/delta/blob/master/src/main/scala/org/apache/spark/sql/delta/storage/S3SingleDriverLogStore.scala#L163
[3] https://github.com/delta-io/delta/blob/master/src/main/scala/org/apache/spark/sql/delta/storage/S3SingleDriverLogStore.scala#L118
[4]https://issues.apache.org/jira/browse/HADOOP-16490

**Comment by rvd8345** [comment]
@igorcalabria I have tried running this on hadoop 2.8.5, Hadoop 3.2 but keep getting Java FileNotFound exceptions on S3 for few files. The Hadoop issue above says that it is fixed in Hadoop 3.3.

But is there anyway to make this work on Hadoop 2.8.5 or 3.2? I am using S3a as recommended. Delta lake version 0.6.1

**Comment by steveloughran** [comment]
s3a createFile stopped doing a HEAD on overwrite=true in hadoop-3.3.0. However, its moot as the log store is doing an (expensive) exists check anyway.

Even with hadoop 3.3.x, the driver code should swap the !overwrite check with the 100+millis head request for performance alone, let alone the risk of 404 caching

**Comment by zsxwing** [comment]
@steveloughran Thanks for the comment. We need to check the existence of an object before writing. `S3SingleDriverLogStore` has an in-memory cache to remember all written files but the cache is gone after restarting JVM. Any suggestion to implement the same semantics of `overwrite = false` without the risk of 404 caching in S3A?

**Comment by steveloughran** [comment]
it's a tricky one. My PoV is "use something like S3Guard for that consistent view". Because if you are finding files through any list operation, you are at risk there.

Otherwise, maybe a sequence of
exists
create
while(!exists) { sleep(exponential rate) }

that way -you can be confident that when the code is exited, it will exist. You just need to sleep for long enough for it to appear. HADOOP-16490 shows the times and values which appear to work there, which is done at read time.

**Comment by igorcalabria** [comment]
We "fixed" this issue with a small patch that allows writing delta in a custom path, so we're able to keep data on s3 but use a smallish HDFS cluster to store the delta files

I just got tired of dancing around s3 limitations

**Comment by steveloughran** [comment]
> We "fixed" this issue with a small patch that allows writing delta in a custom path, so we're able to keep data on s3 but use a smallish HDFS cluster to store the delta files

That's how the S3A staging committer moves the list of files to materialize from workers to the job manager/driver. create-no-overwrite is up there with atomic-rename as features we coders take for granted.

**Comment by zsxwing** [comment]
S3 now provides strong consistency: https://www.amazonaws.cn/en/new/2020/amazon-s3-now-delivers-strong-read-after-write-consistency-automatically-for-all-applications/

Closing this.
