### ISSUE TITLE
Convert to Delta

### ISSUE THREAD

**Issue by zhangxinjian123** [delta-io/delta#328]
According to the delta Lake API, I successfully converted the hive internal table to delta Lake table. The first question is whether the transformed table is the inner table of hive or the outer surface of hive. Because the data of delta Lake project can't enter hive directly, you need to connect delta Lake table through delta IO / connectors. The second problem is that hive internal tables are transformed into delta Lake tables. Can later delta Lake data directly enter the money table?

**Comment by tdas** [comment]
It's not generally recommended to convert an internal hive table to a Delta table because Hive will probably throw an error when you attempt to query the converted Delta table. Assuming you are using open-source Delta Lake (i.e., not Databricks Delta Lake), Hive metastore will still consider it to be an internal table in Parquet format, so any Hive queries will attempt to read the table as parquet and fail (the json files in the _delta_log directory will cause problems). And it is pretty weird if an internal Hive table cannot be read from Hive, hence I would not recommend do that.

**Comment by pranavanand** [comment]
@zhangxinjian123 were you able to work around the issue?
