### ISSUE TITLE
Issue to integrate with AWS Athena

### ISSUE THREAD

**Issue by rakeshdey0018** [delta-io/delta#398]
I am using delta lakes from databricks, and using storage as AWS s3.. I have created mounted point in DBFS.. 

Everything is fine.. But when I am trying to create symlink_format_manifest in mount folder of DBFS, its showing error

DeltaTable deltaTable = DeltaTable.forPath(spark, '/mnt/folder);
deltaTable.generate("symlink_format_manifest");

Error: 
**java.lang.UnsupportedOperationException: com.databricks.backend.daemon.data.client.DBFSV1.resolvePathOnPhysicalStorage(path: Path)**

But it is working fine when I am hardcoding the S3 bucket instead of /mnt/folder..

Can you please let me know where the issue ? And how It will be possible to create manifest file using dataframe command in DBFS mounted folder

**Comment by tdas** [comment]
I am surprised that you are somehow using DBFSV1. This is a pretty involved issue that directly related to Delta (even though it manifests through Delta). Please contact Databricks support for this issue.

**Comment by rakeshdey0018** [comment]
Thanks @tdas ... Actually I am just trying some coding with Delta lake on S3 storage using Databricks community edition (with DBR 6.4 ).. Then have observed that issue

**Comment by tdas** [comment]
I see. That may explain DBFSV1. The community edition may still be running on DBFSV1 whereas commercial Databricks platform uses DBFSV2. This error won't be an issue on the commercial platform.

That said, with Athena, since you have to deal with full S3 paths anyways, its best to continue with S3 paths even on the Databricks side. Keeps things consistent and easier to reason about.

**Comment by rakeshdey0018** [comment]
Thanks a ton for clearing confusion.
