### ISSUE TITLE
Question for merging different partitions at same time

### ISSUE THREAD

**Issue by mrdotmoon** [delta-io/delta#421]
I have a table which have billions of rows, and partitioned to 4000 partitions, and the jobs may run merge operations on each partition at same time. If I have enough workers machines, 

1. Will the merge operation in different partition block each other?
2. Does Vacuum operation run automatically or I need to run manually?

**Comment by liwensun** [comment]
Hi @mrdotmoon 

1. Should be ok, but make sure you use partition filters in each merge command.

2. You'll need to run vacuum manually.

**Comment by stunax** [comment]
I am having some trouble regarding something similar to this but currently at a much smaller scale.
I have a process looking something like this
```
val partitionedDf = ... Unique rows on combinations of A and Key
.repartitionBy($"A")

partitionedDf
.write
.partitionBy("A")
.format("delta")
.save(tablePath)
spark.sql(s"CREATE TABLE tablePartitionedByA USING DELTA LOCATION '${tablePath}'")

DeltaTable
.forName("tablePartitionedByA")
.as("t")
.merge(
  partitionedDf.as("s"), 
  $"t.A" === $"s.A" && 
  $"t.key" === $"s.key")
.whenMatched().updateAll()
.whenNotMatched().insertAll()
.execute()

//spark.read.table("silver.tablePartitionedByA").count() = 27782211
```
It appears as though every partition is loading the whole delta table instead of each task loading just the partition that makes sense.
If that is not the case, then I do not really have any Idea as to why the merge slow.

I know I could reduce the search space by specifying some restrictions on the merge parameter and make a few passes over the data, but I would very much like a single atomic action.

Any suggestions or explanations so I can figure out what is wrong?

A is a timestamp if it makes any difference. I have also tried partitioning on a date, but it hardly makes a difference except the partitions get somewhat bigger.

Partitions does at a maximum contain around 1 mil records, and many contains just a single entry. Giving the job 20 mins to run, and I hardly ever see a single task finish. 
They do a lot of shuffle writes though.
Each task have done several GB of shuffle writes, while the original save does only some 20 MB for the partitions with lots of data.

**Comment by liwensun** [comment]
@stunax 1) From the code you provided, are you merging the table to itself? `partitionedDf` is the same as `tablePartitionedByA` right?
2) how many unique timestamps are there? We usually don't partition on a column with lots of distinct values like a timestamp.

**Comment by stunax** [comment]
It's just an example, where everything is going to be updated. 
Do not read into that part.

The timestamps are hourly, and could just as well have been a Date column.
I have tried both, and it does not change anything.
In the test data I currently have there is around a years worth of data.
So ~365 or 365*24 partitions, which I know is overkill, but it is more to prove a point.

**Comment by liwensun** [comment]
Hi @stunax Sorry for the delay - somehow missed your response above!

What we could do now is to look at some Merge metrics to see what Merge actually did. Were you able to successfully run a single Merge (without concurrent operations)? You can find the Merge metrics in the Spark UI, or if you are using 0.6.1, you can see the metrics using Describe History, which is nice. There were also some perf improvement for merge in 0.6.1 so i suggest you upgrade if you haven't already.

One thing to check aside from the metrics is that it sounds like having too many partitions may make your target table end up having a lot of files. Note that Delta will need to reconstruct the delta log for the entire table, even if you only need to operate on a single file. Having too many small data files will incur a high cost on the delta log reconstruction, even if your actual merge is super fast.

Let me know if these help.
