### ISSUE TITLE
spark.delta.logStore.class

### ISSUE THREAD

**Issue by thbeh** [delta-io/delta#503]
Hi, if my spark app is using 2 storage type, both S3 and Azure Data Lake Store Gen2, could I put spark.delta.logStore.class=org.apache.spark.sql.delta.storage.AzureLogStore, org.apache.spark.sql.delta.storage.S3SingleDriverLogStore

Thanks in advance

**Comment by zsxwing** [comment]
Currently we don't support this. But this is a great feature request. Ideally, we should be able to pick up the `LogStore` implementation according to the path scheme (hdfs, s3, adls).

**Comment by jeff303** [comment]
Took a crack at this, based on my interpretation (see linked PR)

**Comment by super1ha1** [comment]
Hi, I saw the pull request is  opened for a while,
do you need someone to update the pull request or create a new one?

**Comment by tdas** [comment]
@jeff303 @super1ha1 This has actually been done as part of Delta 1.0 release. @jeff303 our apologies that we didn't make much progress on your PR because reviewing it made us realize that we need to solve other problems first, like make a more stable public LogStore API. That's what we did as part of Delta 1.0 effort. Please look at the release notes for more information - https://github.com/delta-io/delta/releases/tag/v1.0.0

Thank you very much for your effort. And I am closing this issue and associated PR.

**Comment by super1ha1** [comment]
Great!
Thanks @tdas
