### ISSUE TITLE
Merge using only 1 executor

### ISSUE THREAD

**Issue by david-quijano** [delta-io/delta#513]
Hi,
I have been trying to use DeltaTable merge.
My source table and my update table are using 7 files each and the reading is done in 7 executors as expected.
However, the merge is only done in 1 executor.
Is this behavior expected? Is there a way to make it run in parallel?

```
df = spark.read.format('orc').load(update_path)

delta_table = DeltaTable.forPath(spark, delta_path)
(
  delta_table
  .alias('source')
  .merge(
    source = df.alias('update'),
    condition = 'source.c1 = update.c1 and source.c2 = update.c2'
  )
  .whenMatchedUpdate(
    set = {
      'c3': 'update.c3'
    }
  )
  .whenNotMatchedInsertAll()
  .execute()
)
```

**Comment by david-quijano** [comment]
I set `spark.sql.shuffle.partitions` to 1 to get 1 file per partition instead of lots of tiny files. That looks to be the problem.
However, is there a way to get the best of both? Parallel execution and 1 file per partition output?

**Comment by ashokblend** [comment]
we can set spark.databricks.delta.merge.repartitionBeforeWrite.enabled="true". This will repartition merged data based on partition column. Because of this partitioned data will be colocated and will be written to one file per partition

https://github.com/delta-io/delta/blob/3ed57d0668b09d48172b0eb7221f647811657972/src/main/scala/org/apache/spark/sql/delta/commands/MergeIntoCommand.scala#L529

**Comment by zsxwing** [comment]
Yep, using `spark.databricks.delta.merge.repartitionBeforeWrite.enabled` is much better than setting `spark.sql.shuffle.partitions` to 1. See https://docs.delta.io/latest/delta-update.html#performance-tuning for more details.
