### ISSUE TITLE
when to support "DESCRIBE HISTORY" SQL in the open source version of  Delta Lake?

### ISSUE THREAD

**Issue by frank-dkvan** [delta-io/delta#52]
I find we can look at the history of table changes using the DESCRIBE HISTORY command, but this command doesn't work in the open community version

**Comment by tdas** [comment]
Yes, "DESCRIBE HISTORY" does not work in the open source right because Apache Spark's SQL parser and does not support these Delta-specific SQL commands. We will make Scala/Python APIs for describing the history of the table. We are currently focusing on cloud storage support, but after than we will focus on APIs.

**Comment by frank-dkvan** [comment]
> Yes, "DESCRIBE HISTORY" does not work in the open source right because Apache Spark's SQL parser and does not support these Delta-specific SQL commands. We will make Scala/Python APIs for describing the history of the table. We are currently focusing on cloud storage support, but after that we will focus on APIs.

got it! thx!

**Comment by mukulmurthy** [comment]
Support for describing table history is tracked by https://github.com/delta-io/delta/issues/54.

Closing this for now; feel free to reopen if you have follow up questions.
