### ISSUE TITLE
Support for restore operations on DeltaTable

### ISSUE THREAD

**Issue by mrichards-scottlogic** [delta-io/delta#632]
DBR has restore to version and restore to timestamp utility commands.  
https://docs.databricks.com/delta/delta-utility.html#restore-a-delta-table-to-an-earlier-state

Would be great to have these in the OSS version of Delta to take advantage of time travel for ops and quickly resolving data issues.

Technically, it's probably something that we could implement outside of Delta, but I would expect it to be a generally useful feature to include.

**Comment by jaceklaskowski** [comment]
Hi,

Just a thought. Is this equivalent in OSS Delta Lake to read with the
versionAsOf option and overwrite?

Pozdrawiam,
Jacek Laskowski
----
https://about.me/JacekLaskowski
"The Internals Of" Online Books <https://books.japila.pl/>
Follow me on https://twitter.com/jaceklaskowski

<https://twitter.com/jaceklaskowski>

**Comment by jles01** [comment]
Not quite. 
If you do a rollback, the current version is equal to versionOf.  So all parties use the correct version (which was rollbacked). We do not have to make sure each process/pipeline receive the correct versionOf. It would be very difficult in multi tenant, multi cluster environment

**Comment by jaceklaskowski** [comment]
Makes sense. Stretching out my delta muscles with another possible OSS-based solution.

In 0.8.0 they added `DeltaTable.upgradeTableProtocol` operator. That could "shut down" all read and write access for maintenance "rollback" window. You could then remove the versions up to the one for rollback using mere `rm` command.

WDYT?

**Comment by jles01** [comment]
In ideal world it should work as:
All readers when starting to read should have an indicator in sparkSession which version of this table they are using. 
When operator do a command something like "ROLLBACK TO VERSION OF ", what happens
a) all writers get "shutdown". We either gracefully wait or do a hard stop (there probably should be a new type of Transaction exception)
b) we generate a new json manifest file which is copy of the rollback. 
c) all readers still are reading the version from which they started (this needs to be handled by the process). We can have additional parameter if it is a batch read the complete if streaming then do a hard stop

**Comment by jles01** [comment]
@wtfzambo I do not know that. However we can think of not to generate a new json log. Instead of we can create a "technical" transaction on top which would point to the version which we rolled back.

**Comment by wtfzambo** [comment]
@jles01 damn I had missed the notification of your reply.

How would you create a "technical" transaction without generating a new json log?
We need a way to let delta know to ignore latest version and instead read from whatever version specified in the rollback operation.

Second, parallel question: you mention a multi-tenant environment and I don't understand how a RESTORE operation would be different than reading versionAsOf and then overwriting the full table.

**Comment by Maks-D** [comment]
Hi,

As I know for table restore Databricks generates a new transactions (json). This transaction contains all files from "restore" version as an Add operation and all files missed in "restore" version but existent in current as a Delete operation. To generate such transaction we don't need to read\write parquet files and reading _delta_log files is enought.
As for me this has sense, because we should not break transaction history and each transaction should be in delta log.

**Comment by mlecuyer-nd** [comment]
Also interested in this feature.

One usecase we have is if a bad commit makes its way into a table, we would like a way to roll back to the previous state without having to rewrite the entire table.

Real example: Back filling some partitioned data into a table. Was about 5TB of data across ~50k files. One job accidentally got triggered twice. Having to read in the entire table (about 20TB or so) from a previous version and rewriting it would be very costly and time consuming. Being able to rollback by just modifying the commit log would save a lot of time and effort. 

The workaround we found was to manually go and remove transaction log files (since they hadn't been compacted yet) and then do manual cleanup on the files that were "lost" to delta by parsing the transaction log

**Comment by jles01** [comment]
Hi

i have a PR ready for This just need to add testing. Generały I create additional log file with a Column restoreToVersion. And If reader sees it it will read from that version skipping everything in between. Also when writer Wants to save transaction and the restore appeared it will throw an exception

**Comment by wtfzambo** [comment]
@jles01 I think that the [logic](https://github.com/delta-io/delta/issues/632#issuecomment-970666385) proposed by @Maks-D is more appropriate, given how Delta logs are structured.

It would also work better for people integrating delta table with Athena / Presto for what regards generating manifest symlink files.

**Comment by Maks-D** [comment]
@mrichards-scottlogic I've create PR to add Scala API for DeltaTable using logic described [here](https://github.com/delta-io/delta/issues/632#issuecomment-970666385). SQL and python API will be added in a separate PR if Scala API PR be merged

**Comment by mrichards-scottlogic** [comment]
Thanks @Maks-D for impementing this!
