### ISSUE TITLE
Document Databricks Delta features not supported in OSS Delta

### ISSUE THREAD

**Issue by amesar** [delta-io/delta#77]
Explicitly describe those Databricks features that are not supported in OSS Delta. There repeated slack questions about this especially regarding Delta-specific SQL commands.

For example:
- DESCRIBE HISTORY my_table
- DESCRIBE DETAIL my_table
- SELECT * FROM my_table VERSION AS OF 5 
- Merge syntax

**Comment by SpaceRangerWes** [comment]
Looks like VACUUM and HISTORY have been added to the programmatic API in v0.3.0 https://docs.delta.io/0.3.0/delta-utility.html

MERGE is also in the programmatic API https://docs.delta.io/0.3.0/delta-update.html#upsert-into-a-table-using-merge

What are current features that individuals are looking for that are not yet implemented? I know Z-ORDER is one and is not on the roadmap.

**Comment by SpaceRangerWes** [comment]
After some minor comparison, the difference in features between delta on databricks and oss are

1. manifest files
2. data skipping
3. compaction
4. auto optimize
5. native parquet reader
6. Z-ordering

**Comment by Samarendra-Sahoo** [comment]
Thanks for sharing this information. Is there plan to bring these features
to OSS version?

**Comment by marmbrus** [comment]
We are discussing this over on #129 and will add some language to clarify the roadmap the readme.

In general though it is our goal to open source all APIs that are required to correctly run a program against a Delta Lake table. This will take some time, as some (SQL time travel) require first adding new APIs to Spark for us to leverage. In some cases we might end up working with other engines to add the same support, rather than waste time open sourcing a workaround (manifests).

Many of the performance features listed, however, are deeply tied to the specifics of Databricks runtime and platform, so there are no plans to open source them at this time.

**Comment by btbbass** [comment]
I think this is the most interesting one:
 * compaction
(not necessarily automatic):

Will the compaction be supported in the oss, as for example the vacuum ?

**Comment by marmbrus** [comment]
@btbbass, vacuum is already supported as of 0.3.0.  For instruction of how to implement compaction, see the answer here: https://github.com/delta-io/delta/issues/49#issuecomment-526343434
