### ISSUE TITLE
Real Time Insert and Update

### ISSUE THREAD

**Issue by arezamoosavi** [delta-io/delta#829]
I really enjoyed working with delta tables on minio hive presto spark; in a batch mode and I am curious to know whether the delta tables are proper for spark or flink event processing with many insert and update events?
Thanks

**Comment by tdas** [comment]
Absolutely yes! Continuous bulk changes (aka streaming) is the biggest use case where you want transactional guarantees so that readers can read consistent snapshots while the writers can continue updating. That's exactly what Delta Lake was designed for!! 

Delta Lake + Structured Streaming happily read/write to Delta tables at arbitrary scales, GB, and TBs easily, with some more tuning and optimization PBs too. See the [delta docs](https://docs.delta.io/latest/delta-streaming.html) for more code details.

Flink write support is in [progress](https://github.com/delta-io/connectors/issues/111), so soon this will be possible with Flink as well.

**Comment by arezamoosavi** [comment]
Thanks, It is super cool!!
Also I dont know wether I used the upsert correctly or not; does this line check all the data for upserting?
And in real time how is this gonna be optimized?

```
(delta_table.alias("t1").merge(
        sdf.alias("t2"),
        "t1.timestamp = t2.timestamp").whenMatchedUpdateAll()
     .whenNotMatchedInsertAll().execute())

```
[the original file](https://github.com/arezamoosavi/AcidOnSpark-ETL/blob/main/airflow/dags/etl/spark_update.py)

**Comment by tdas** [comment]
this will indeed check all the data to find the matches. 
you can optimize this a bit with a bit of manual tweaking. if the table is partitioned, say by date and if you know your sdf to be upserted has data only for certain partitions / dates, then you can add that in the merge condition. 

```
(delta_table.alias("t1").merge(
        sdf.alias("t2"),
        "t1.timestamp = t2.timestamp AND t1.date IN (.......) ").whenMatchedUpdateAll()
     .whenNotMatchedInsertAll().execute())
```

**Comment by tdas** [comment]
There are some perf improvement pointers already in the docs... have you checked? 
https://docs.delta.io/latest/delta-update.html#performance-tuning

**Comment by arezamoosavi** [comment]
thanks for sharing, yeah I am going to check it.
so it is clear for me that there upserting optimization is more manual and based on partitioning of the delta files.
