### ISSUE TITLE
Writing multi-part checkpoints

### ISSUE THREAD

**Issue by pdonath** [delta-io/delta#837]
The protocol defines a possibility to write multi-part checkpoints. In the current version of open-source Delta Lake (1.0.0), Spark always writes a single checkpoint file. It can become a bottleneck, especially in a streaming application. I suggest to implement such multi-part checkpoints writing with a configurable parameter to control the number of parts (eg. based on a size of the previous checkpoint or a number of files in the table).

**Comment by tdas** [comment]
Even though we write a single checkpoint, since they are in Parquet format which is splittable, the checkpoint can be read by multiple tasks in parallel. However, they would split at the granularity of row groups which can be very large, thus limiting the parallelism. So multiple checkpoints may help in certain scenarios. Do you have a specific scenario where you think this will help? Can you elaborate?

Would be lovely to see contributions from the community.

**Comment by pdonath** [comment]
Reading is a smaller problem. I can always reduce the size of parquet row groups. The problem is fast writing. For me the greatest feature of Delta Lake is unification of streaming and batch processing using Spark. My scenario is more less like the following:
I get a huge amount of messages (millions per second) in a Kafka topic. I want to aggregate them in 1-minute windows in many groups and then detect anomalies. Anomaly detection model is trained periodically based on aggregates from the past, so I need to store these aggregates for very long time. I compact files once a week, but still the checkpoint size is 100-200 MB.
The problem is that every 10 micro batches (every 2-5 minutes) Spark needs to create a new checkpoint. Currently it can be done only by a single executor, so this single executor needs to write 100-200 MB. The result is that one per ten micro batches takes 2-3 times as long and this has a bad effect on anomaly detection.

**Comment by Kimahriman** [comment]
This would be very useful in combination with #923. In my case it can sometimes take several minutes to read a snapshot because reading a hundreds of MB checkpoint will be done by 1 task. The downside of having the checkpoints as parquet is it gets affected by other parquet settings. We use a 512mb row group size on our compaction, which then can translate to the checkpoint. Also, for large tables we use 512+mb partition bytes size, which gets translates to reading the checkpoint too.

It would be great to be able to tune the checkpoint splitting and reading of checkpoints in a way that can ignore these settings and force a certain level of parallelism
