### ISSUE TITLE
Describe logRetentionDuration in PROTOCOL

### ISSUE THREAD

**Issue by wjones127** [delta-io/delta#888]
If I understand right, delta log files older than `logRetentionDuration` may be deleted if they are no longer needed. This is documented at [docs.delta.io](https://docs.delta.io/latest/delta-batch.html#data-retention), but is not mentioned in the PROTOCOL.md. 

Which reader version does this behavior go back to? Version 1?

**Comment by scottsand-db** [comment]
Hi @wjones127, thanks for your question.

Do you think this configuration needs to be documented in `PROTOCOL.md`? Wouldn't that then mean that all of our configurations should be documented in `PROTOCOL.md` too?

You can check out the [reader version requirements section](https://github.com/delta-io/delta/blob/master/PROTOCOL.md#requirements-for-readers) of the `PROTOCOL.md` which documents what features new reader versions introduce. Since `logRetentionDuration` isn't mentioned there for version 2, you can tell that this behaviour is in version 1.

**Comment by wjones127** [comment]
@scottsand-db 
> Do you think this configuration needs to be documented in PROTOCOL.md? Wouldn't that then mean that all of our configurations should be documented in PROTOCOL.md too?

You're right that we don't need to document this setting in particular. But I think the behavior of deleting old log files should be documented. When I read the protocol I thought reading checkpoints was an optional optimization. But this setting means it's required for a reader, and that readers shouldn't consider delta tables missing old log corrupt or invalid.

**Comment by scottsand-db** [comment]
Would you like to submit a short PR adding this description?
