### ISSUE TITLE
delta writing to adls gen2 file system

### ISSUE THREAD

**Issue by ashishkshukla** [delta-io/delta#898]
Hi,
I am trying to write to delta table with underline file system as Azure DataLake Gen2. 
But getting below error while saving the dataframe.

            2022-01-18 16:43:48 Driver [INFO ] OptimisticTransaction - [tableId=2ecf0fde-9980-4246-9d7d-4849477fffcf] Attempting to commit version 0 with 4 actions with Serializable isolation level

           Exception while processing:

         java.lang.IllegalStateException: Versions (Vector(0, 0)) are not contiguous.

              at org.apache.spark.sql.delta.DeltaErrors$.deltaVersionsNotContiguousException(DeltaErrors.scala:550)

              at org.apache.spark.sql.delta.SnapshotManagement.verifyDeltaVersions(SnapshotManagement.scala:370)

              at org.apache.spark.sql.delta.SnapshotManagement.verifyDeltaVersions$(SnapshotManagement.scala:365)

              at org.apache.spark.sql.delta.DeltaLog.verifyDeltaVersions(DeltaLog.scala:59)

              at org.apache.spark.sql.delta.SnapshotManagement.getLogSegmentForVersion(SnapshotManagement.scala:160)

              at org.apache.spark.sql.delta.SnapshotManagement.getLogSegmentForVersion$(SnapshotManagement.scala:82)

              at org.apache.spark.sql.delta.DeltaLog.getLogSegmentForVersion(DeltaLog.scala:59)

              at org.apache.spark.sql.delta.SnapshotManagement.$anonfun$updateInternal$1(SnapshotManagement.scala:289

Environments-

Spark - 3.1.2
Delta - 1.0.0

Please someone help me here.

**Comment by zsxwing** [comment]
This looks like an Azure DataLake Gen2 connector bug. Could you try the following code to see the results in your spark shell?
```scala
import org.apache.hadoop.fs._
val path = new Path("<adls-path>/_delta_log")
val fs = path.getFileSystem(spark.sessionState.newHadoopConf)
println(fs.listStatus(path).toList)
```
The issue like this is usually because the above code returns incorrect results.

**Comment by ashishkshukla** [comment]
Hi @zsxwing ,
Above code snippet is returning the output correctly.

To elaborate more ,
I am using hadoop-azure3.2.1 library for delta with Azure DataLake connectivity and when I am running standalone program things are running fine.  

I am trying to use above libraries in a web based project hosted on tomcat. Several other dependencies are also there but I have made sure, it has hadoop-azure and delta versions are of the same as used in standalone program.
While saving the dataframe I can see it is creating snappy.parquet file in the given adls path and also a json file in _delta_log (like 0000000000x.json) . But then I get above Exception and it makes program exit.

**Comment by zsxwing** [comment]
Hm, this could be some library dependency issue (e.g., hadoop-azure requires to use a library X at version Y, but the same library is also in your web based project but with version Z). Would you be able to try the code snippet in the web based project hosted on tomcat?

**Comment by ashishkshukla** [comment]
yes @zsxwing  . it is giving same result. 

I'll relook into the dependencies .
BTW one thing I observed . In the logs it is printing below line when running a standalone program-

`INFO DelegatingLogStore: LogStore org.apache.spark.sql.delta.storage.AzureLogStore is used for scheme abfss`

but in my project above log is not coming. Rest are same until the Exception comes.

Can this might be the issue of not loading log store correctly for abfss scheme.
Can we pass some configuration to spark to make sure it picks abfss log store.

**Comment by ashishkshukla** [comment]
Hi @zsxwing  .Found the root cause.
We support multiple delta sources like S3, HDFS, ADLS in our project and below property was set in Spark conf

`conf.set("spark.delta.logStore.class", "org.apache.spark.sql.delta.storage.S3SingleDriverLogStore");`

We upgraded delta to 1.0.0 recently and now above conf is deprecated and if we still use the same then scheme based dynamic delta store delegation wont happen .It seems it was still using S3 delegation and thus causing .

Thanks , we can close this now.

**Comment by zsxwing** [comment]
Great to hear you fixed the issue 😄

**Comment by KarthikL96** [comment]
Is it possible to create Delta tables using local only. i.e without Databricks

**Comment by ashishkshukla** [comment]
@KarthikL96 Yes . We can create delta tables without using databricks.

**Comment by KarthikL96** [comment]
Hi @ashishkshukla , 
Thank you for responding. 
I'm trying to access ADLS gen2 and create delta tables using pyspark from my local. 
**The configurations I've used is
Spark-3.3.0
Python-3.10
delta-spark-2.3
azure-storage-8.6.6
hadoop-azure-3.3.1
hadoop-azure-datalake-3.3.3
hadoop-common-3.3.3

Below code is the one I'm using.**

from pyspark.sql import SparkSession
from delta.tables import *
spark = (
    SparkSession.builder.master("local[*]")
    .config("spark.jars.packages", "io.delta:delta-core_2.12:2.3.0")
    .config("spark.sql.extensions", "io.delta.sql.DeltaSparkSessionExtension")
    .config("spark.sql.catalog.spark_catalog", "org.apache.spark.sql.delta.catalog.DeltaCatalog")
    .config("spark.delta.logStore.class", "org.apache.spark.sql.delta.storage.S3SingleDriverLogStore")
    .config("spark.driver.memory", "4g")
    .config("spark.executor.memory", "4g")
    .config("spark.jars", r"C:\Users\Proem Sports\Documents\Jupyter notebooks\jars\mysql-connector-j-8.0.31.jar")
    .config("spark.jars", r"C:\Users\Proem Sports\Documents\Jupyter notebooks\jars\azure-storage-8.6.6.jar") 
    .config("spark.jars", r"C:\Users\Proem Sports\Documents\Jupyter notebooks\jars\hadoop-azure-3.3.1.jar")
    .config("spark.jars", r"C:\Users\Proem Sports\Documents\Jupyter notebooks\jars\hadoop-azure-datalake-3.3.3.jar")  
    .config("spark.jars", r"C:\Users\Proem Sports\Documents\Jupyter notebooks\jars\hadoop-common-3.3.3.jar")    
    .config("spark.sql.legacy.parquet.int96RebaseModeInRead", "CORRECTED")
    .config("spark.sql.legacy.parquet.int96RebaseModeInWrite", "CORRECTED")
    .config("spark.sql.legacy.parquet.datetimeRebaseModeInRead", "CORRECTED")
    .config("spark.sql.legacy.parquet.datetimeRebaseModeInWrite", "CORRECTED")
    .config("spark.sql.execution.arrow.pyspark.enabled", "TRUE")
    .config("spark.sql.legacy.timeParserPolicy", "CORRECTED")
    .config("spark.sql.warehouse.dir", r"C:\Users\Proem Sports\Documents\Jupyter notebooks\Dev_scripts\metastore_db")
    .config("spark.sql.execution.arrow.pyspark.enabled", "true")
    .config("spark.delta.commitInfo.merge.enabled", "true")
    .config("fs.azure.createRemoteFileSystemDuringInitialization", "false")
    .config("fs.azure", "org.apache.hadoop.fs.azure.NativeAzureFileSystem")
    .config("fs.azure.account.auth.type", "SharedKey")
    .config("fs.azure.account.key.proemdatalake.blob.core.windows.net", "account-key")
    .enableHiveSupport()
    .getOrCreate()
)
spark.conf.set("fs.azure.account.auth.type."+storage_account_name+".dfs.core.windows.net", "OAuth")
spark.conf.set("fs.azure.account.oauth.provider.type."+storage_account_name+".dfs.core.windows.net", "org.apache.hadoop.fs.azurebfs.oauth2.ClientCredsTokenProvider")
spark.conf.set("fs.azure.account.oauth2.client.id."+storage_account_name+".dfs.core.windows.net", client_id)
spark.conf.set("fs.azure.account.oauth2.client.secret."+storage_account_name+".dfs.core.windows.net", client_secret)
spark.conf.set("fs.azure.account.oauth2.client.endpoint."+storage_account_name+".dfs.core.windows.net", "https://login.microsoftonline.com/"+directory_id+"/oauth2/token")

df=spark.read.format("csv").load("abfss://"container_name"@"storage_account_name".dfs.core.windows.net/RAW_DATA/MERHCHANDISE/MERCH_20230424_.csv",header=True,inferSchema=True)
df.write.format("delta").option("overwriteSchema", "true").option('delta.columnMapping.mode', 'name').save("abfss://"container_name"@"storage_account_name".dfs.core.windows.net/tables/delta_table1")

_I'm able to read the csv file successfully from ADLSgen2, but writing the same file as delta table I'm getting an error saying
Py4JJavaError: An error occurred while calling o120.save.
: org.apache.spark.sql.delta.DeltaIllegalStateException: Versions (Vector(0, 0)) are not contiguous. _

There are no solutions to the above error as fas as I've researched. I would like your help on the above issue, so that I can avoid using databricks as i dont have data of that level. Please help me in resolving the above issue So that I'll be able to deliver the project successfully.
