### ISSUE TITLE
Delta LogStore Refactor - S3SingleDriverLogStore

### ISSUE THREAD

**Issue by scottsand-db** [delta-io/delta#952]
Refactor [S3SingleDriverLogStore](https://github.com/delta-io/delta/blob/master/core/src/main/scala/org/apache/spark/sql/delta/storage/S3SingleDriverLogStore.scala) to Java for the new `delta-storage` artifact.

For the project overview, requirements, and how to contribute, please see the  [#951 - Delta LogStore Refactor - Project Plan](https://github.com/delta-io/delta/issues/951).

**Comment by ahlag** [comment]
Hi @scottsand-db, I would like to give this a try.
I'm unable to assign myself cause I don't have the permission.

**Comment by scottsand-db** [comment]
@ahlag done

**Comment by ahlag** [comment]
@scottsand-db 
Just one quick question. How do you test if the code is working locally?

**Comment by scottsand-db** [comment]
@ahlag sorry just saw this. You should be adding a public test, e.g. `PublicS3SingleDriverLogStore` into `LogStoreSuite.scala` just like `PublicHDFSLogStoreSuite`.

**Comment by scottsand-db** [comment]
If you have a solution, please push the branch and make a PR so I can take a look :)

**Comment by ahlag** [comment]
@scottsand-db 
Really sorry for taking so much time. I'm still picking up Scala and Java on the side.

Just want to confirm something. (Really sorry for the beginner questions.)
1. In this PR, PublicLogStoreSuite is extended from LogStoreSuiteBase. I was wondering do I have to implement this now because you have closed the PR.
https://github.com/scottsand-db/delta/blob/4a88e4d88f8601ee32032261899de152f0b39ff3/core/src/test/scala/org/apache/spark/sql/delta/LogStoreSuite.scala#L353-L379

2. How do you want the object Scala classes to be refactored?

**Comment by vkorukanti** [comment]
Closed via https://github.com/delta-io/delta/commit/fab016e874532cad4de17f1077dbdc860548be9a
